name: testing
on:
  push:
    branches:
      - testing
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build-testing:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      target: server
      variant: hci
      configuration: nvidia
      tag: testing
