name: stable
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build-stable:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      target: server
      variant: hci
      configuration: nvidia
      tag: stable
